// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdteqherbfpndfjpghvh.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkdGVxaGVyYmZwbmRmanBnaHZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0NDExMDYsImV4cCI6MjA4MzAxNzEwNn0.sOBUVfUSJHuFceD_7VXu7i5Wf4_67AOfEf7NuM9M1bI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});